#pragma once

#include <Windows.h>
#include <iostream>
#include <conio.h>
#include <string>
#include <vector>

#define WORLD_SIZE		30
#define UI_POS_X		WORLD_SIZE + 3
#define LOG_POS_Y		WORLD_SIZE + 3

#define TEXT_FOREGROUND_BLUE		 FOREGROUND_BLUE
#define TEXT_FOREGROUND_BLUE_INT	 FOREGROUND_BLUE | FOREGROUND_INTENSITY
#define TEXT_FOREGROUND_GREEN		 FOREGROUND_GREEN
#define TEXT_FOREGROUND_GREEN_INT	 FOREGROUND_GREEN | FOREGROUND_INTENSITY
#define TEXT_FOREGROUND_RED			 FOREGROUND_RED
#define TEXT_FOREGROUND_RED_INT		 FOREGROUND_RED | FOREGROUND_INTENSITY
#define TEXT_FOREGROUND_YELLOW		 FOREGROUND_RED | FOREGROUND_GREEN
#define TEXT_FOREGROUND_YELLOW_INT	 TEXT_FOREGROUND_YELLOW | FOREGROUND_INTENSITY
#define TEXT_FOREGROUND_MAGENTA		 FOREGROUND_BLUE | FOREGROUND_RED
#define TEXT_FOREGROUND_MAGENTA_INT	 TEXT_FOREGROUND_MAGENTA | FOREGROUND_INTENSITY
#define TEXT_FOREGROUND_CYAN		 FOREGROUND_BLUE | FOREGROUND_GREEN
#define TEXT_FOREGROUND_CYAN_INT	 FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY
#define TEXT_FOREGROUND_GRAY	     TEXT_FOREGROUND_RED | TEXT_FOREGROUND_BLUE | TEXT_FOREGROUND_GREEN
#define TEXT_FOREGROUND_WHITE		 TEXT_FOREGROUND_GRAY | FOREGROUND_INTENSITY
#define TEXT_FOREGROUND_BLACK		 0

#define TEXT_BACKGROUND_BLUE		 BACKGROUND_BLUE
#define TEXT_BACKGROUND_BLUE_INT	 BACKGROUND_BLUE | BACKGROUND_INTENSITY
#define TEXT_BACKGROUND_GREEN		 BACKGROUND_GREEN
#define TEXT_BACKGROUND_GREEN_INT	 BACKGROUND_GREEN | BACKGROUND_INTENSITY
#define TEXT_BACKGROUND_RED			 BACKGROUND_RED
#define TEXT_BACKGROUND_RED_INT		 BACKGROUND_RED | BACKGROUND_INTENSITY
#define TEXT_BACKGROUND_YELLOW		 BACKGROUND_RED | BACKGROUND_GREEN
#define TEXT_BACKGROUND_YELLOW_INT	 BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY
#define TEXT_BACKGROUND_MAGENTA		 BACKGROUND_BLUE | BACKGROUND_RED
#define TEXT_BACKGROUND_MAGENTA_INT	 BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY
#define TEXT_BACKGROUND_CYAN		 BACKGROUND_BLUE | BACKGROUND_GREEN
#define TEXT_BACKGROUND_CYAN_INT	 BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_INTENSITY
#define TEXT_BACKGROUND_GRAY		 TEXT_BACKGROUND_RED | TEXT_BACKGROUND_BLUE | TEXT_BACKGROUND_GREEN
#define TEXT_BACKGROUND_WHITE		 TEXT_BACKGROUND_GRAY | BACKGROUND_INTENSITY
#define TEXT_BACKGROUND_BLACK		 0