#pragma once

#include <Windows.h>
#include <iostream>
#include <conio.h>
#include <fstream>
#include <string>
#include <vector>
#include <memory>
#include <math.h>

#define WORLD_SIZE		30								//	정사각형 맵의 크기

#define BEZEL_WIDTH		2
#define WIDTH_MULTIPLY	2
#define UI_POS_X		(WORLD_SIZE + 2) * WIDTH_MULTIPLY			//	UI 작성 시작위치
#define LOG_POS_Y		WORLD_SIZE + 3					//	Log 작성 시작위치

#define UI_WITDH		10
#define LOG_HEIGHT		7

#define TEXT_FOREGROUND_BLUE		 FOREGROUND_BLUE
#define TEXT_FOREGROUND_BLUE_INT	 FOREGROUND_BLUE | FOREGROUND_INTENSITY
#define TEXT_FOREGROUND_GREEN		 FOREGROUND_GREEN
#define TEXT_FOREGROUND_GREEN_INT	 FOREGROUND_GREEN | FOREGROUND_INTENSITY
#define TEXT_FOREGROUND_RED			 FOREGROUND_RED
#define TEXT_FOREGROUND_RED_INT		 FOREGROUND_RED | FOREGROUND_INTENSITY
#define TEXT_FOREGROUND_YELLOW		 FOREGROUND_RED | FOREGROUND_GREEN
#define TEXT_FOREGROUND_YELLOW_INT	 TEXT_FOREGROUND_YELLOW | FOREGROUND_INTENSITY
#define TEXT_FOREGROUND_MAGENTA		 FOREGROUND_BLUE | FOREGROUND_RED
#define TEXT_FOREGROUND_MAGENTA_INT	 TEXT_FOREGROUND_MAGENTA | FOREGROUND_INTENSITY
#define TEXT_FOREGROUND_CYAN		 FOREGROUND_BLUE | FOREGROUND_GREEN
#define TEXT_FOREGROUND_CYAN_INT	 FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY
#define TEXT_FOREGROUND_GRAY	     TEXT_FOREGROUND_RED | TEXT_FOREGROUND_BLUE | TEXT_FOREGROUND_GREEN
#define TEXT_FOREGROUND_WHITE		 TEXT_FOREGROUND_GRAY | FOREGROUND_INTENSITY
#define TEXT_FOREGROUND_BLACK		 0

#define TEXT_BACKGROUND_BLUE		 BACKGROUND_BLUE
#define TEXT_BACKGROUND_BLUE_INT	 BACKGROUND_BLUE | BACKGROUND_INTENSITY
#define TEXT_BACKGROUND_GREEN		 BACKGROUND_GREEN
#define TEXT_BACKGROUND_GREEN_INT	 BACKGROUND_GREEN | BACKGROUND_INTENSITY
#define TEXT_BACKGROUND_RED			 BACKGROUND_RED
#define TEXT_BACKGROUND_RED_INT		 BACKGROUND_RED | BACKGROUND_INTENSITY
#define TEXT_BACKGROUND_YELLOW		 BACKGROUND_RED | BACKGROUND_GREEN
#define TEXT_BACKGROUND_YELLOW_INT	 BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY
#define TEXT_BACKGROUND_MAGENTA		 BACKGROUND_BLUE | BACKGROUND_RED
#define TEXT_BACKGROUND_MAGENTA_INT	 BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY
#define TEXT_BACKGROUND_CYAN		 BACKGROUND_BLUE | BACKGROUND_GREEN
#define TEXT_BACKGROUND_CYAN_INT	 BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_INTENSITY
#define TEXT_BACKGROUND_GRAY		 TEXT_BACKGROUND_RED | TEXT_BACKGROUND_BLUE | TEXT_BACKGROUND_GREEN
#define TEXT_BACKGROUND_WHITE		 TEXT_BACKGROUND_GRAY | BACKGROUND_INTENSITY
#define TEXT_BACKGROUND_BLACK		 0


enum ETag
{
	actor		=	1	<<	0,
	character	=	1	<<	1,
	player		=	1	<<	2,
	monster		=	1	<<	3,
	boss		=	1	<<	4,
	projectile	=	1	<<	5,
	effect		=	1	<<	6,
	environment	=	1	<<	7,
};
